### ISSUE TITLE
Docker-compose bootstrap

### ISSUE THREAD

**Issue by ratosh** [aiarena/local-play-bootstrap#1]
Using docker-compose to start docker instead of bash files:

```
version: "3.9"
services:
  arena-client:
    volumes:
      - ./config.py:/root/aiarena-client/config.py
      - ./:/root/aiarena-client/host
      - D:/Games/StarCraft II/Maps:/root/StarCraftII/maps
    image: aiarena/arenaclient
 ```
`docker-compose` on console to start.
